site_name: Energy-GNoME
site_url: https://paolodeangelis.github.io/Energy-GNoME/
site_author: Paolo De Angelis, Giulio Barletta
site_description: >-
  AI-Driven Screening and Prediction for Advanced Energy Materials

repo_name: GitHub
repo_url: https://github.com/paolodeangelis/Energy-GNoME/
edit_uri: edit/main/docs/


# copyright: Copyright &copy; 2024 Small Lab

extra_css:
  - stylesheets/extra.css
  - stylesheets/custom/layout/hero.css
  - stylesheets/custom/layout/down_arrow.css
  - stylesheets/custom/tooltipster/tippy.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/wiki_hover.js
  - javascripts/down_arrow.js

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/img/logo_alt.png
  favicon: assets/img/favicon.png
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        # icon: material/brightness-auto
        icon: material/link
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: gnome
      primary: gnome
      accent: gnome
      toggle:
        # icon: material/brightness-7
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: gnome
      accent: gnome
      toggle:
        icon: material/toggle-switch-off
        # icon: material/brightness-4
        name: Switch to light mode
  features:
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.instant.preview
    # - navigation.sections
    # - navigation.expand
    - navigation.top
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.home
    - navigation.tracking
    - navigation.path
    - navigation.indexes
    - navigation.footer
    - toc.follow
    # - toc.integrate
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - search.highlight
    - search.share
    - search.suggest
    - header.autohide
    - announce.autohide
    # - announce.dismiss

  hide:
    # - announce
watch:
  - includes

extra:
  homepage: https://paolodeangelis.github.io/Energy-GNoME/
  status:
    new: Recently added
    deprecated: Deprecated
  social:
    - icon: extra/SMaLL_logo_small
      link: https://www.polito.it/small/
    - icon: extra/PoliTO_logo
      link: https://www.polito.it/
    - icon: fontawesome/brands/github
      link: https://github.com/paolodeangelis/Energy-GNoME/
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/small_polito
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/small-lab/

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - footnotes
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      pygments_lang_class: true
      auto_title: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
        - includes/important_links.md
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - docs/overrides/.icons
plugins:
  - search
  # - glightbox
  # - git-authors
  - git-revision-date-localized:
      type: timeago
      timezone: Europe/Rome
      locale: en
      fallback_to_build_date: false
      enable_creation_date: true
  # - git-committers:
  #     enabled: true
  #     repository: paolodeangelis/Energy-GNoME
  #     branch: main
  #     token: !!python/object/apply:os.getenv ["MKDOCS_GIT_COMMITTERS_APIKEY"]
  - minify:
      minify_html: true
  - mkdocstrings:
      default_handler: python
      docstring_style: google
      handlers:
        python:
          options:
            show_root_heading: true
            show_root_toc_entry: true



nav:
  - Home: index.md
  - Dashboards:
    - Database Dashboards: apps/index.md
    - Cathodes:
        - User guide: apps/cathodes/userguide.md
        - Dashboard: apps/cathodes/dashboard.html
    - Perovskites:
        - User guide: apps/perovskites/userguide.md
        - Dashboard: apps/perovskites/dashboard.html
    - Thermoelectrics:
        - User guide: apps/thermoelectrics/userguide.md
        - Dashboard: apps/thermoelectrics/dashboard.html
  - About the Database: about_db/index.md
  - Documentation:
    - Overview: docs/index.md
    - Getting started: docs/getting-started.md
    - Modules:
        - Datasets: docs/modules/dataset.md
  - Contribute: contribute/index.md
  - How to cite: ./how_to_cite.md
