authors:
  team:
    name: Energy-GNoME Team
    description: Creator
    avatar: ./assets/img/people/team.png
  giuliobarl:
    name: Giulio Barletta
    description: Creator
    avatar: ./assets/img/people/gbarletta.jpg
  paolodeangelis:
    name: Paolo De Angelis
    description: Creator
    avatar: ./assets/img/people/pdeangelis.jpg
  giotre:
    name: Giovanni Trezza
    description: Creator
    avatar: ./assets/img/people/gtrezza.jpg
  pietroasinari:
    name: Pietro Asinari
    description: Creator
    avatar: ./assets/img/people/pasinari.png
  eliochiavazzo:
    name: Eliodoro Chiavazzo
    description: Creator
    avatar: ./assets/img/people/echiavazzo.png
